### ISSUE TITLE
Choose a project topic

### ISSUE THREAD

**Issue by martarozek** [martarozek/jnp3#1]

**Comment by martarozek** [comment]
A page with user generated content which other users can rate. 
For example: 
- photo services (add a place where you can buy analog films, develop films, buy photo accessories, other users verify by a thumb-up or a thumb-down and add comments),
- bike parkings (add a place where a bike stand would be helpful, other users verify it by a thumb-up or a thumb-down and add comments).
  Both of them need a Google Maps integration but it would be just one not too big frontend task. I like these ideas because they are very simple and I would use these apps if they existed :D.

**Comment by przemokraw** [comment]
The second project seems to be interesting:)

**Comment by martarozek** [comment]
For the bike parking app there could be three cases: no stands, too few stands, stupid stands that let you lock only the wheel. The design could be very simple, very map-based. The database would need to keep users, points submitted by users, ratings and comments. I think it's so simple that we could code it in a week and then focus on other technologies.

**Comment by GraczykowskiMichal** [comment]
The second project is interesting for me as well, so I think we can make a choice :)

**Comment by martarozek** [comment]
Great! Just to make sure everything is clear: I'm happy to do the Django backend on my own, it won't take me long and I like it a lot. Are you OK with the frontend? Or do you want to split it somehow? It would be great to have the base app ready asap.
