### ISSUE TITLE
Choose frontend technology

### ISSUE THREAD

**Issue by martarozek** [martarozek/jnp3#5]
We should also choose the main frontend developer in our team, someone who will know the most about it and will take care that everything is working.

**Comment by GraczykowskiMichal** [comment]
Moja propozycja to Angular:
- bardzo popularna technologia, niższy próg wejścia niż React
- wiele tutoriali do Angulara + Django, szczególnie że robimy RESTa

**Comment by martarozek** [comment]
OK, angular2? 😄

**Comment by GraczykowskiMichal** [comment]
Fajnie by było, ale z pewnością jest mniej tutoriali i mniejsze community, więc może być trochę trudniej. Pozostałbym przy 1.
